### PR TITLE
Docs: Add logo to README

### PR DESCRIPTION
**Pull request by Dup4**
Maybe consider adding a logo to the README?

Look like this:

image

You can check by this [link](https://github.com/Dup4/domjudge).

### CODE REVIEW

**Comment by vmcj** [comment]
When you set GitHub to dark mode this doesn't look nice.

**Comment by Dup4** [comment]
> When you set GitHub to dark mode this doesn't look nice.

Yes, you are right.

**Comment by nickygerritsen** [comment]
We already have the logo's in Git: https://github.com/DOMjudge/domjudge/tree/main/doc/logos

**Comment by Dup4** [comment]
> We already have the logo's in Git: https://github.com/DOMjudge/domjudge/tree/main/doc/logos

Yes, I saw them but they are all transparent logos.

When we turn on dark mode, it becomes unrecognizable, like below:

image

But in light mode, it will be much better, like below:

image

You can check by this [link](https://github.com/Dup4/domjudge/tree/9b1e5e3407a595a5fc7c4a6e881fa1b1b6428f3c)

So my idea is, we can add a logo with a white background, like [this](https://github.com/Dup4/domjudge/blob/main/doc/logos/DOMjudgelogo-with-white-background.png).

Then in dark mode, the displayed effect will be slightly better.

image

I'm just making a suggestion, it's up to you to accept this PR or not.

**Review by thijskh — CHANGES_REQUESTED** [review]
I prefer using an existing image in the repo. Also there must be an alt tag in an image.

**Comment by thijskh** [comment]
You could choose not to display the logo when in dark mode (DOMjudgelogo.svg#gh-light-mode-only) but that's also not a very nice solution.

I can't think of a better solution now than just to add the logo with the white background next to the logos we have. But probably the real solution would be to redesign our logo (files) so we have a higher quality svg and two variants based on background. We'd also need that if we would ever implement a dark mode in DOMjudge itself (#922).

**Pull request merged**
