### PR TITLE
Hide samples for interactive problems.

### LINKED ISSUE #926: Consider hiding sample download for interactive problems
As mentioned in #920 and also discussed during the CCS Specs standards call, for interactive problems the sample data is mostly useful for the validator and not for teams. The sample data mostly contains information for the validator to run.

I believe it makes more sense to hide the download of the samples for interactive problems for this reason.
#920 makes it that we can have attachments if one wants multiple data to pass to some testing tool.

Any thoughts?

### PR DESCRIPTION
**Pull request by nickygerritsen**
Fixes #926

### CODE REVIEW

**Comment by vmcj** [comment]
Might be unrelated, but in your branch it looks like we don't add the sample data in the zip when exporting.

**Review by vmcj — APPROVED** [review]
So I think it looks good, minor thing is that when testing I found that `.interaction` files are not put in the exported zip. I think we should mention this in https://github.com/DOMjudge/domjudge/issues/227 and not fix this in this PR.

I'm just thinking if it makes sense to provide the `.interaction` file in this case so people can download it and test their solution against it. In BAPC we most of the time get an attachment which does this interaction for you.

I'm talking about the case where a team doesn't get this provided. For those cases we provide the sample `.{in,ans}` files for normal problems so people can `diff` their solution against the sample in the (printed) PDF so it makes sense to also provide this via download to handle both types of problems in the same way?

Reason for not doing this besides the extra work would be that these interactions can be non-deterministic such that you can't easily reproduce the interaction and possibly debug (as a team) if you're doing the right thing. This problem already exists for normal problems if the output can be unordered for example.

**Comment by nickygerritsen** [comment]
I’m not sure I agree.

First of all we don’t even import the interaction file, since we don’t need it.

Second of all I’m not sure how useful the interaction file is. You can’t really diff it against anything since there is no way to get the same format locally?

Third I don’t think the problem package format says anything about needing to expose it?

**Comment by vmcj** [comment]
> Second of all I’m not sure how useful the interaction file is. You can’t really diff it against anything since there is no way to get the same format locally?

Correct me if I'm wrong, but having the file and copying and pasting will get you less errors. And if you would start your program and paste the jury input you can more easily test.

If we can expose things which could be useful for teams I think we should do it. So to me the question is if its useful, not if the spec requires it.

> I’m not sure I agree.
> 
> First of all we don’t even import the interaction file, since we don’t need it.
> 
> Second of all I’m not sure how useful the interaction file is. You can’t really diff it against anything since there is no way to get the same format locally?
> 
> Third I don’t think the problem package format says anything about needing to expose it?

Ok, lets discuss in person at some point. Not important for this PR.

**Pull request merged**
