### PR TITLE
When the scoreboard is requested to be static, disable Ajax refreshes

### PR DESCRIPTION
**Pull request by thijskh**

### CODE REVIEW

**Comment by nickygerritsen** [comment]
Any reason why we drop Ajax support for static scoreboards? I tested it with an externally hosted scoreboard and it worked...

**Comment by thijskh** [comment]
I don’t understand how that can work? Where to send the xhr call to? Since the webserver will only serve static content?

**Comment by nickygerritsen** [comment]
The call gets sent to the page itself. I then look in the html content (since indeed we only get that data) for some specific divs and replace them onto the current page

**Comment by thijskh** [comment]
Alright. Then my fix is not necessary I guess

**Pull request closed without merging**
