### PR TITLE
Add command to load development fixtures

### PR DESCRIPTION
**Pull request by mvr320**
@nickygerritsen is there an easier way of doing this? I needed this to check why an Unit test was failing.

### CODE REVIEW

**Comment by nickygerritsen** [comment]
I’m not sure what `bin/console doctrine:fixtures:load` has as options? Maybe you van provide it a path or something

**Comment by mvr320** [comment]
> 
> 
> I’m not sure what `bin/console doctrine:fixtures:load` has as options? Maybe you van provide it a path or something

I check that before and I couldn't find it, so I would like this to be merged.

**Review by nickygerritsen — APPROVED** [review]

**Comment by meisterT** [comment]
Looks good but please also mention in the developer docs.

**Comment by mvr320** [comment]
> 
> 
> Looks good but please also mention in the developer docs.

I added a small section for it,

**Pull request merged**
