### PR TITLE
Use anchors to build 2 database jobs

### PR DESCRIPTION
**Pull request by mvr320**
Test the integration test also against the traditional MySQL server. In
the future we can extend this with different judgedaemons or different
base images.

This does yield a speed penalty currently.

### CODE REVIEW

**Review by nickygerritsen — APPROVED** [review]
Sweet

**Comment by mvr320** [comment]
Removed the non-generated integration test and added the comments back.

**Comment by mvr320** [comment]
@nickygerritsen can you check if the migration makes sense (Do I indeed have to change this much for the Entity files?)

Yesterday evening this terminated correctly, so I dont expect this build to fail and should be in mergeable state.

**Review by nickygerritsen — COMMENTED** [review]
There is a `webapp/src/Controller/Jury/.ProblemController.php.swp` file still left.

Did you generate the migration using `webapp/bin/console doctrine:migrations:diff`? I'm not sure if that works with renaming columns though.

**Pull request merged**
