### PR TITLE
Last poll time is a decimal, so Doctrine uses strings by default when…

### PR DESCRIPTION
**Pull request by nickygerritsen**
… fetching from the database.

The Symfony debug bar complained about this.

### CODE REVIEW

**Review by vmcj — COMMENTED** [review]
Why can't we steer doctrine to use a proper float? I find this ugly without the explanation

**Comment by nickygerritsen** [comment]
Decimals aren't safe to put in a float since you loose precision, so they use strings. if you want floats, use `FloatType`.
Which we could do here but then the database column type will change as well to `DOUBLE PRECISISON` from `DECIMAL(X,Y)`

**Comment by nickygerritsen** [comment]
> Decimals aren't safe to put in a float since you loose precision, so they use strings. if you want floats, use `FloatType`. Which we could do here but then the database column type will change as well to `DOUBLE PRECISISON` from `DECIMAL(X,Y)`

If we are going to change the column type I'd vote to do that in a different PR btw. But I'm not sure if we should do that at all.

**Review by meisterT — APPROVED** [review]
I think this is just making this one field align with all of our other `decimal` fields, so I believe it is Ok to merge.

We can discuss whether we want to change it in general separately, ISTR that @eldering looked into this at some point.

**Pull request merged**
