### PR TITLE
docs: Update problem-format.rst

### PR DESCRIPTION
**Pull request by qwedc001**
small fix to correct the outdated problem_package_format url

also working on other good first issues.

### CODE REVIEW

**Comment by qwedc001** [comment]
hmm,just found that version 2023-07-draft has added multiple new parameters to some files.
wondering if legacy(icpc) suits domjudge better

**Comment by eldering** [comment]
Thanks for finding the broken link. Indeed, as you also noticed there were a lot of changes to the `2023-07-draft` problem package format this weekend (I was involved in that). The aim is to release what in `2023-07-draft` as a stable specification around the ICPC World Finals in Astana in September, but for now it would be more accurate to link to the legacy ICPC version indeed.

**Comment by eldering** [comment]
See https://github.com/DOMjudge/domjudge/pull/2653

**Comment by qwedc001** [comment]
okay,so shall I just close this one?

**Pull request closed without merging**
