### PR TITLE
Make APIs return correctly typed values.

### PR DESCRIPTION
**Pull request by nya3jp**
Since our DB returns all retrieved values as strings, our API
also returns string values for most of entries. It is okay for
PHP clients because of weak typing, but accessing from other
strongly typed languages is difficult and unpredictable.

### CODE REVIEW

**Comment by thijskh** [comment]
Yes, useful :+1:

**Comment by eldering** [comment]
Looks useful and good code to me.
Just some minor suggestions, see: https://github.com/eldering/domjudge/commits/typed-api
In particular, I think the variable $jid returned from the SQL query in judgings_POST() still needs to be cast to int, right?

**Comment by nya3jp** [comment]
Thanks Jaap for reviewing!

I merged your update to my pull request. And about $jid, since $jid is used only to fill $row, it is okay to leave as a string. But maybe:

     $row['judgingid']   = safe_int($jid);

is more clearer as I did in the latest patch?

**Comment by eldering** [comment]
I overlooked the line
$row['judgingid']   = safe_int($row['judgingid']);
in your original patch. Sorry for the confusion.

Merged it.

**Comment by nya3jp** [comment]
Thanks!

**Pull request closed without merging**
