### PR TITLE
Drop py3 from extensions.

### PR DESCRIPTION
**Pull request by meisterT**

### CODE REVIEW

**Comment by nickygerritsen** [comment]
Tests will fail, since we have test submissions ending in .py3 which will now not submit, so we need to change the number of successful submissions in the integration test somewhere.

**Comment by vmcj** [comment]
So why don't we fail?

**Comment by meisterT** [comment]
Because it is already rejected before: https://gitlab.com/DOMjudge/domjudge/-/jobs/3106311834#L3149

**Comment by meisterT** [comment]
(and the number of "unverified" submissions is what we check and that doesn't change)

**Comment by meisterT** [comment]
I have added another commit to delete the old test files with the old extensions.

**Review by vmcj — APPROVED** [review]

**Review by nickygerritsen — APPROVED** [review]

**Pull request merged**
