### PR TITLE
Simplify test case run display.

### PR DESCRIPTION
**Pull request by meisterT**
Before:
image

and

image

After:
image

and

image

### CODE REVIEW

**Comment by meisterT** [comment]
Another part of https://github.com/DOMjudge/domjudge/pull/2452

**Comment by vmcj** [comment]
I liked the earlier location for the JS toggle more, what was your argumentation for moving it?

**Comment by meisterT** [comment]
> I liked the earlier location for the JS toggle more, what was your argumentation for moving it?

I would argue it is one of the least used buttons on the page and by moving it to the right it is less in the way of the commonly used flow of reading.

**Comment by eldering** [comment]
> > I liked the earlier location for the JS toggle more, what was your argumentation for moving it?
> 
> I would argue it is one of the least used buttons on the page and by moving it to the right it is less in the way of the commonly used flow of reading when scanning the page.

I agree with @vmcj that I don't like the new position of the JS toggle, especially because it might easily be out of sight.

**Comment by meisterT** [comment]
> especially because it might easily be out of sight.

haha, that was my goal, so success I guess :smiling_face_with_tear:  - but I guess I am in the minority here

I will play around with a couple options.

**Comment by eldering** [comment]
> What about _always_ displaying it, but somehow muted?

Looks good!

Just wondering if the `s211` could be moved to the end (like the `judge remaining` button above) and also make it clear that that's the previous submission, e.g. with `previous: s211`. Not sure that improves things though.

**Comment by vmcj** [comment]
> What about _always_ displaying it, but somehow muted?
> 
> For example: image

I like this already more, but would argue might show the differences less flushed out to directly show the information. To steer someone in seeing the right information.

**Comment by meisterT** [comment]
@vmcj I like that idea, also when we are in shadowing mode, but I suggest to address it in follow-up changes as it has many edge cases.

I moved the text to the back of the row as Jaap requested.

image

**Review by vmcj — APPROVED** [review]

**Pull request merged**
