### PR TITLE
Add view for queue tasks. Fixes #1378.

### LINKED ISSUE #1378: Create a view for queue tasks
As mentioned by @meisterT

### PR DESCRIPTION
**Pull request by nickygerritsen**
Screenshots:
image
image

### CODE REVIEW

**Review by thijskh — APPROVED** [review]
I have not reviewed every line but overall looks good in approach and presentation. Just wondering why the info in the judgestask table is so limited. Maybe not everything, but at least the `type` for example?

**Comment by thijskh** [comment]
if you view /jury/queuetasks/1/judgetasks, then the judgedaemon handles those tasks, then reload the page you get `App\Entity\QueueTask object not found by the @ParamConverter annotation.`

Reproduce like this: Stop judgedaemon. Submit something. View judgetasks of the new queuetask. Start judgedaemon. Reload page.

**Comment by thijskh** [comment]
Well, it still exists, it's just set to valid=0?

**Comment by nickygerritsen** [comment]
> Well, it still exists, it's just set to valid=0? Throwing this exception seems kind of harsh.

No. The *queue task* is gone. That’s the whole purpose of that table: to never have too much data. The judge tasks might be there but not the queue task it belonged ro

**Comment by thijskh** [comment]
Alright, maybe then just say so? It now looks like you've ran into a bug, getting an obscure exception for doing something that seems normal to me. It can also happen if you click something in the Queue task overview that has meanwhile been processed.

**Comment by nickygerritsen** [comment]
> Alright, maybe then just say so? It now looks like you've ran into a bug, getting an obscure exception for doing something that seems normal to me. It can also happen if you click something in the Queue task overview that has meanwhile been processed.

Yea so my suggestion with the notice makes sense. I will do it

**Review by thijskh — APPROVED** [review]
Great, let's merge it, and improve it later if necessary

**Pull request merged**
