### PR TITLE
Use (descriptive) name instead of shortname in HTML title on scoreboa…

### PR DESCRIPTION
**Pull request by meisterT**
…rds.

Reported by @jsannemo.

### CODE REVIEW

**Review by nickygerritsen — APPROVED** [review]

**Comment by thijskh** [comment]
I think this was intentional as browser tabs have very limited space so a shortname is more informative there than _The International Collegiate Programming Contest North Western European Regional Contest Sponsored by International Business Machines Hosted by Nicky Gerritsen Honored by Upsilon Pi Epsilon_

**Comment by meisterT** [comment]
But `dress` or `finals` is a really not descriptive name.

**Comment by thijskh** [comment]
The shortname shows in other places e.g. the menu bar so it makes sense to choose the short names at least somewhat descriptively e.g. `NWERC2022`

**Comment by nickygerritsen** [comment]
We do only show it in the menu bar for teams if there is >1 contest. For jury we do always show it. I think the finals contest is called `finals` for years, and I am not sure if we should change that...

**Pull request closed without merging**
