### PR TITLE
Team clarification form updates.

### PR DESCRIPTION
**Pull request by nickygerritsen**
Screenshot for the last commit:
image
@meisterT is this what you wanted?

### CODE REVIEW

**Comment by nickygerritsen** [comment]
I think both are possible. Let me try

**Comment by nickygerritsen** [comment]
New screenshot:
image

I also applied this to the jury btw.

**Comment by meisterT** [comment]
That looks good, I am considering doing a follow-up change similar to this:
image

**Comment by nickygerritsen** [comment]
> That looks good, I am considering doing a follow-up change similar to this: image

Feel free to push to my branch

**Comment by nickygerritsen** [comment]
LGTM, when CI passes I will merge.

**Pull request merged**
