### PR TITLE
If a main class can't be detected or found, do not make this a compile error.

### PR DESCRIPTION
**Pull request by nickygerritsen**
It has been decided that this made more sense.

As discussed via mail with the WF judges. This should also mimic the PC<sup>2</sup> behaviour.

### CODE REVIEW

**Review by vmcj — APPROVED** [review]
Fine for the WFs, and makes sense to apply the same on underlying contests.

Not saying I agree with the logic but this is only for a very special edgecase so fine by me.

**Comment by nickygerritsen** [comment]
We decided to merge this to a `wfsharm` (or similar) branch for now when it is created.

**Comment by meisterT** [comment]
This is now obsolete after we merged #2129

**Comment by nickygerritsen** [comment]
Yes closing

**Pull request closed without merging**
