### PR TITLE
Use coffin to indicate jail

### PR DESCRIPTION
**Pull request by mvr320**
The checkmark was not aligned with the one used for the outcome.

### CODE REVIEW

**Comment by eldering** [comment]
I think 🔒 would be a better choice.

**Comment by meisterT** [comment]
It's not a check mark, it's a square root symbol 😉

But replacing with a 🔒 sounds good

**Comment by thijskh** [comment]
🛅
▶️&⏹
💂‍♀️
🥕

**Comment by thijskh** [comment]
For the three occurrences in order:
🔏, 🔒, 🔓

**Comment by mvr320** [comment]
> It's not a check mark, it's a square root symbol wink

I really should have seen that... still it doesn't look nice in my screen ;)

**Pull request merged**
