### PR TITLE
Prepare 8.2.1 patch release

### PR DESCRIPTION
**Pull request by vmcj**
I'm not sure if we should pick all these, but the commit messages refer to now closed issues.

Probably it makes sense if more than 1 person does the review as a lot of variables were renamed and it could be the commits doing the rename might not have been cherry-picked.

### CODE REVIEW

**Comment by eldering** [comment]
I think that 1699d754526766aa265de75690944722e8f7b268 and fa1786ccb462197ffad466598a619906614e08e9 strictly speaking should not have been backported, as they're not really fixes. But since they're very convenient and not critical code, I'm fine with it as is.

Should 2f77ae4d6815889408eab9128125c85cdc6545b3 be added. As I understand it, this is only needed with Symfony 6.2. Same with 8ab9632f0a8508ccc70e0e6c097d42f00c5944fc?

c11f63d6801d01b6126744dd75d990affa5c4bab is a performance improvement, not a bugfix, and requires some (untested) code changes, so I'd not backport this. Then also f8043f1b8df62378b980f76a8d3e44ca6683959e, 0d8cf525095670d634c703a8b458da3367d78a43 should be removed (fixes on top of the first commit).

I don't think e3da3dda3872a2221ff2b41a3fc5b7f46ee67e1c should be backported: it's not really a bugfix, and it's not tested. Also cbd8bc76602535f048ba3054f2dc5e12e57c9831 is just code cleanup, so should not be backported I think.

Also 7c9ee53bdc9350dde1f2e2e8792d46b38b5d4faa should not be backported: it's not really a bugfix and it also depends on other commits from the PR because of brittle Doctrine state

Some commits that I think should also be backported:
- 46449e88870e2212f9bef00284192b2b763714bc
- ab07c2b617730ad81415a56692f24ff6ebd105d6, 7c169ae5f66c59f98fa7ec0cb1a4faf496cfac96, 9a05f117ddd8714887b393cb97541c2b6ca3a242 @nickygerritsen ?
- d02a07e8d86da0b8bafc383382b87ae09dfc648b @nickygerritsen ?
- 7727c930cb8df76615867af563453c685bcf1d8b @thijskh ?
- 9cc324e9c6bb12d90e162d3e52914b9bd0d40aaf @nickygerritsen ?
- d0c2487095d69a4c944c9cd965a4ba20beb3eb96
- 5cd488cde1b2a2f62f6e27bc66d539dd200aa5ca
- 5dd35383dc8ed495a5a0ef14065e4a7fa046fc30
- 8231f1291effadb328161462dd86a9f5223fc025

I was considering 181ae06a5625611274f7217be85cfd28d5f351b4 also for backporting as it fixes a real bug, but it also introduces DB changes, so maybe not ideal. WDYT @meisterT ?

**Comment by vmcj** [comment]
> I think that [1699d75](https://github.com/DOMjudge/domjudge/commit/1699d754526766aa265de75690944722e8f7b268) and [fa1786c](https://github.com/DOMjudge/domjudge/commit/fa1786ccb462197ffad466598a619906614e08e9) strictly speaking should not have been backported, as they're not really fixes. But since they're very convenient and not critical code, I'm fine with it as is.

The reason I added it was that It broke your system by overwriting the `.netrc` if I remember correctly.
> 
> Should [2f77ae4](https://github.com/DOMjudge/domjudge/commit/2f77ae4d6815889408eab9128125c85cdc6545b3) be added? As I understand it, this is only needed with Symfony 6.2. Same with [8ab9632](https://github.com/DOMjudge/domjudge/commit/8ab9632f0a8508ccc70e0e6c097d42f00c5944fc).

You're right, I'll take them out.
> 
> [c11f63d](https://github.com/DOMjudge/domjudge/commit/c11f63d6801d01b6126744dd75d990affa5c4bab) is a performance improvement, not a bugfix, and requires some (untested) code changes, so I'd not backport this. Then also [f8043f1](https://github.com/DOMjudge/domjudge/commit/f8043f1b8df62378b980f76a8d3e44ca6683959e), [0d8cf52](https://github.com/DOMjudge/domjudge/commit/0d8cf525095670d634c703a8b458da3367d78a43) should be removed (fixes on top of the first commit).

Ok, I considered slow performance a bug, but I agree its untested (and might be stretching on the concept of what is a bug)

> 
> I don't think [e3da3dd](https://github.com/DOMjudge/domjudge/commit/e3da3dda3872a2221ff2b41a3fc5b7f46ee67e1c) should be backported: it's not really a bugfix, and it's not tested. Also [cbd8bc7](https://github.com/DOMjudge/domjudge/commit/cbd8bc76602535f048ba3054f2dc5e12e57c9831) is just code cleanup, so should not be backported I think.

Ok, SGTM
> 
> Also [7c9ee53](https://github.com/DOMjudge/domjudge/commit/7c9ee53bdc9350dde1f2e2e8792d46b38b5d4faa) should not be backported: it's not really a bugfix and it also depends on other commits from the PR because of brittle Doctrine state

I was already in doubt if it was because of the new migration or if this was a bug. So I'll take it out.
> 
> Some commits that I think should also be backported:
> 
>     * [46449e8](https://github.com/DOMjudge/domjudge/commit/46449e88870e2212f9bef00284192b2b763714bc)
> 
>     * [ab07c2b](https://github.com/DOMjudge/domjudge/commit/ab07c2b617730ad81415a56692f24ff6ebd105d6), [7c169ae](https://github.com/DOMjudge/domjudge/commit/7c169ae5f66c59f98fa7ec0cb1a4faf496cfac96), [9a05f11](https://github.com/DOMjudge/domjudge/commit/9a05f117ddd8714887b393cb97541c2b6ca3a242) @nickygerritsen ?
> 
>     * [d02a07e](https://github.com/DOMjudge/domjudge/commit/d02a07e8d86da0b8bafc383382b87ae09dfc648b) @nickygerritsen ?
> 
>     * [7727c93](https://github.com/DOMjudge/domjudge/commit/7727c930cb8df76615867af563453c685bcf1d8b) @thijskh ?
> 
>     * [9cc324e](https://github.com/DOMjudge/domjudge/commit/9cc324e9c6bb12d90e162d3e52914b9bd0d40aaf) @nickygerritsen ?

I think we don't add fields for patch releases, so that was the reason to not include it.
> 
>     * [d0c2487](https://github.com/DOMjudge/domjudge/commit/d0c2487095d69a4c944c9cd965a4ba20beb3eb96)
> 
>     * [5cd488c](https://github.com/DOMjudge/domjudge/commit/5cd488cde1b2a2f62f6e27bc66d539dd200aa5ca)
> 
>     * [5dd3538](https://github.com/DOMjudge/domjudge/commit/5dd35383dc8ed495a5a0ef14065e4a7fa046fc30)
> 
>     * [8231f12](https://github.com/DOMjudge/domjudge/commit/8231f1291effadb328161462dd86a9f5223fc025)
> 
> 
> I was considering [181ae06](https://github.com/DOMjudge/domjudge/commit/181ae06a5625611274f7217be85cfd28d5f351b4) also for backporting as it fixes a real bug, but it also introduces DB changes, so maybe not ideal. WDYT @meisterT ?

I'm not 100% confident that I can properly cherry-pick that one and not make mistakes in case of failures.

**Comment by meisterT** [comment]
> I was considering [181ae06](https://github.com/DOMjudge/domjudge/commit/181ae06a5625611274f7217be85cfd28d5f351b4) also for backporting as it fixes a real bug, but it also introduces DB changes, so maybe not ideal. WDYT @meisterT ?

I am reluctant to cherry pick this one in a patch release.

**Comment by thijskh** [comment]
>     * [7727c93](https://github.com/DOMjudge/domjudge/commit/7727c930cb8df76615867af563453c685bcf1d8b) @thijskh ?

Yes

**Comment by nickygerritsen** [comment]
ab07c2b617730ad81415a56692f24ff6ebd105d6, 7c169ae5f66c59f98fa7ec0cb1a4faf496cfac96, 9a05f117ddd8714887b393cb97541c2b6ca3a242 make sense.

d02a07e8d86da0b8bafc383382b87ae09dfc648b, https://github.com/DOMjudge/domjudge/commit/9cc324e9c6bb12d90e162d3e52914b9bd0d40aaf I'm also fine with, but the former doesn't really break. The latter does though.

**Comment by vmcj** [comment]
>     * [8231f12](https://github.com/DOMjudge/domjudge/commit/8231f1291effadb328161462dd86a9f5223fc025)
> 

This one doesn't cherry-pick in the current state

**Review by nickygerritsen — APPROVED** [review]

**Review by eldering — APPROVED** [review]

**Pull request merged**
