### PR TITLE
Enable joining teams in self-registration; see #869

### PR DESCRIPTION
**Pull request by ykazakov**
Upon self-registration there will be an additional
option to either select a team to which the user
may join, or to crate a new team

Only teams which categories allow for self-registration
will be offered for selection.

### CODE REVIEW

**Review by thijskh — CHANGES_REQUESTED** [review]
As per discussion in issue #869, not ready in current form

**Comment by ykazakov** [comment]
@thijskh What about #872? You could pull out the commit for #869 if you think it is not ready.

**Comment by mvr320** [comment]
@ykazakov what is your plan with this PR? Should it stay open?

**Comment by ykazakov** [comment]
@mvr320 looks like the code has diverge significantly. I do not have time to resolve the conflicts, and there appears to be little interests in #869 and #872 anyway.

**Pull request closed without merging**
