### PR TITLE
Displaying whether to Process Awards field on jury’s contents page

### PR DESCRIPTION
**Pull request by shuibinlong**
This is the bug fix for #1109. Last time I forgot to modify jury/contests page for this feature, so I try to fix it, the display scene is the same as process balloons.

Before.

After.

### CODE REVIEW

**Review by meisterT — APPROVED** [review]

**Comment by meisterT** [comment]
The change itself looks good, can you rebase it on top of master?

**Comment by shuibinlong** [comment]
> The change itself looks good, can you rebase it on top of master?

This is the master branch I had fentch it just now, so the changes only 1 file. XD : )

**Comment by thijskh** [comment]
The "after" screenshot looks broken. The number of problems column is missing and the edit button is in that column now.

**Comment by shuibinlong** [comment]
> The "after" screenshot looks broken. The number of problems data is missing and the edit button is in that column now.

Sorry, it seems that my browser's cache problem, it fixed now.

**Comment by thijskh** [comment]
I've used `git am` to apply the relevant two commits to DOMjudge main and squashed them into db8e64b95be1bf4156399b3bfd7c37acf85625df.

I think the branch got a bit messy, it might be because (a) we have renamed our main branch from master to `main` and (b) you created the new feature on your master branch, it's probably better to create a new branch in your repo for each change you'd like to propose (e.g. `feature/show-process-awards-on-contests-page`).

In any case, thanks for your contribution!

**Comment by shuibinlong** [comment]
> I've used `git am` to apply the relevant two commits to DOMjudge main and squashed them into [db8e64b](https://github.com/DOMjudge/domjudge/commit/db8e64b95be1bf4156399b3bfd7c37acf85625df).
> 
> I think the branch got a bit messy, it might be because (a) we have renamed our main branch from master to `main` and (b) you created the new feature on your master branch, it's probably better to create a new branch in your repo for each change you'd like to propose (e.g. `feature/show-process-awards-on-contests-page`).
> 
> In any case, thanks for your contribution!

Sounds reasonable, I will pay more attention to this problem in next contributions. Thank you~

**Pull request closed without merging**
