### PR TITLE
Default behaviour will change July22

### PR DESCRIPTION
**Pull request by vmcj**

### CODE REVIEW

**Comment by nickygerritsen** [comment]
This is not the best commit message ever. Better to at least link to https://getcomposer.org/doc/06-config.md#allow-plugins or something.

**Comment by vmcj** [comment]
> This is not the best commit message ever. Better to at least link to https://getcomposer.org/doc/06-config.md#allow-plugins or something.
I'll update the message with something better.

More important, is this the fix we want?

**Comment by nickygerritsen** [comment]
For flex for sure. I'm not sure what the other plugin does?

**Comment by vmcj** [comment]
composer/package-versions-deprecated: It shows us which installed libs are out of support

Its not something I've installed myself, so i'm also fine with not enabling it.

**Review by nickygerritsen — APPROVED** [review]

**Pull request merged**
