### PR TITLE
Fix public scoreboard banner check without active contest. Fixes #1417.

### LINKED ISSUE #1417: If there is no active contest at this time, accessing the public page will return `500 Internal Server Error`
NOTE: If this is a _discussion starter_, you need any _installation help_ or have a _question_ on how to accomplish something,
rather post at [our discussion channel](https://www.domjudge.org/chat) or send an email to our
[DOMjudge-devel mailinglist](https://www.domjudge.org/mailman/listinfo/domjudge-devel)
instead of filing an issue here.

### Description of the problem

> Replace this line with a short description.

When all contests are finished and all contests are inactive status, then go to the `public page(/domjudge/public)`, it will show `500 Internal Server Error`.

Shouldn't the expected result be that there are currently no active contests or something instead of showing `500 Internal Server Error`?

### Your environment

> Include details about your installation here.
> - DOMjudge version (e.g. 7.0.0 or a github commit hash)
> - Operating system / Linux distribution and version (e.g. Ubuntu 18.04)
> - Webserver (e.g. Apache or nginx)

- Ubuntu 20.04
- Nginx

### PR DESCRIPTION
**Pull request by nickygerritsen**

### CODE REVIEW

**Comment by thijskh** [comment]
This keeps on breaking. So probably best to add a testcase for the public page without an active contest

**Comment by nickygerritsen** [comment]
Yes we should. I can do that on this pr

**Comment by nickygerritsen** [comment]
> Yes we should. I can do that on this pr

Done, was easy enough.

**Review by thijskh — APPROVED** [review]
Just fix the codespell issue and we should be good to go

**Pull request merged**
