### PR TITLE
Add option to start/freeze/unfreeze/... on the contest page.

### PR DESCRIPTION
**Pull request by meisterT**

### CODE REVIEW

**Comment by meisterT** [comment]
Example:
image

**Review by nickygerritsen — APPROVED** [review]

**Review by vmcj — CHANGES_REQUESTED** [review]
Can they be the same width?

**Comment by meisterT** [comment]
> Can they be the same width?

Happy to do if you know the CSS :magic_wand:

**Comment by vmcj** [comment]
> > Can they be the same width?
> 
> Happy to do if you know the CSS 🪄

min-width, max-width width?

**Comment by meisterT** [comment]
> > > Can they be the same width?
> > 
> > 
> > Happy to do if you know the CSS 🪄
> 
> min-width, max-width width?

Done.

**Review by vmcj — APPROVED** [review]
LGTM

**Pull request merged**
