### PR TITLE
Fail gracefully if browser doesn't support ResizeObserver

### PR DESCRIPTION
**Pull request by tom93**
The current Firefox ESR release (68.8.0) doesn't support it yet.

### CODE REVIEW

**Comment by nickygerritsen** [comment]
@mvr320 this is one for you I think. Any opinion?

**Comment by mvr320** [comment]
Yes, it does not fix the problem why I introduced the feature, so I would propose fixing by using a different implementation.

**Comment by thijskh** [comment]
@mvr320 SInce it's a more helpful UI but does not actually break anything in older browsers, I would also think it's fine to accept that you get this if you have a more recent browser, and not if you don't.

**Comment by mvr320** [comment]
@thijskh I think in this case when you need the ResizeObserver you have resized the page so the header can end up everywhere, as at that moment its a fixed style object. So I'm not sure if that should be something which is accepted. I think I can get the same behaviour with onresize, but I did not find time yet to test this. If this is currently blocking somewhere I'm fine with making the time this week but otherwise it will take some time.

**Comment by tom93** [comment]
@mvr320 No rush.
For me it appears to work fine without ResizeObserver, even when I resize the page.
It only breaks if I manually change the height of the top navbar using the DOM inspector, and I'm not sure if that can happen in normal circumstances.

**Comment by thijskh** [comment]
After discussion with @mvr320: this PR improves the situation so can be merged; time permitting he will come with a further improvement later.

**Pull request merged**
