### PR TITLE
Registration

### PR DESCRIPTION
**Pull request by matous-volf**
- Added new options to configuration.
- Increased length of a configuration name to 64 characters.
- Updated the registration form.

### CODE REVIEW

**Comment by matous-volf** [comment]
wrong repo, sorry

**Comment by vmcj** [comment]
Hi @matous-volf, are any of those commits maybe relevant for the main repo? What was your usecase that you had names of 32+ characters?

Your commit with the number of clarifications in the menu was maybe relevant to us?

**Comment by matous-volf** [comment]
Hi, I don't quite know, we had some name trimming problems in the past.

**Comment by matous-volf** [comment]
Update: we needed the name "allow_custom_team_name_registration" (35 chars). :)

**Pull request closed without merging**
