### PR TITLE
Sort teams on clarification for by identifier.

### PR DESCRIPTION
**Pull request by nickygerritsen**
As requested by @baierjan.

### CODE REVIEW

**Comment by nickygerritsen** [comment]
The question is if we want this at all. Jan likes it, but does everyone?

**Comment by eldering** [comment]
> The question is if we want this at all. Jan likes it, but does everyone?

I guess it depends, but I think the request makes sense: if you mainly reference teams by their IDs then it is really annoying to go through a list sorted by names.

But I also think we should be consistent: don't sort one list by ID and another by name. So maybe create a configuration setting that controls the (default) sorting attribute, both in such dropdown lists but also on pages. Then the question is: do we only apply that to teams or also affiliations, categories, problems, ...

**Comment by nickygerritsen** [comment]
> > The question is if we want this at all. Jan likes it, but does everyone?
> 
> I guess it depends, but I think the request makes sense: if you mainly reference teams by their IDs then it is really annoying to go through a list sorted by names.
> 
> But I also think we should be consistent: don't sort one list by ID and another by name. So maybe create a configuration setting that controls the (default) sorting attribute, both in such dropdown lists but also on pages. Then the question is: do we only apply that to teams or also affiliations, categories, problems, ...

I like this idea of having a global setting, but I'm not sure about sorting all entities.

**Comment by nickygerritsen** [comment]
See #2817 for the proper way to do this.

**Pull request closed without merging**
