### PR TITLE
permanent settings for judgehost consistency

### PR DESCRIPTION
**Pull request by thuvh**
As the documents, all settings will be lost if you reboot the server. This commit give some instructions to permanents settings.

### CODE REVIEW

**Comment by thijskh** [comment]
Thanks, very useful. But is it an idea to make the instructions so that it's permanent from the start? That is, replace all with: add line to sysctl.conf; run `sysctl -p`?

**Comment by thuvh** [comment]
Yes, it make permanent from start. After add the line to sysctl.conf, you can use sysctl -p to reload from config file.

**Comment by thijskh** [comment]
Could you change the PR to reflect that?

**Comment by thijskh** [comment]
I've merged it but squashed the two commits together: 97333e71b04dcfea2fc8bbcab43bedfb5980542b.
Thanks for your contribution!

**Pull request closed without merging**
