### PR TITLE
PSR fixes

### PR DESCRIPTION
**Pull request by vmcj**

### CODE REVIEW

**Comment by meisterT** [comment]
Is there a simple command to bring all (changed) code into compliance?

**Comment by vmcj** [comment]
> Is there a simple command to bring all (changed) code into compliance?

For other PRs? I use phpcbf for that and check if I agree with the new look. But I think now that most stuff is done that we have less annotations so it is easier to see for the one opening the PR if they agree with the comment.

**Comment by nickygerritsen** [comment]
> > Is there a simple command to bring all (changed) code into compliance?
> 
> For other PRs? I use phpcbf for that and check if I agree with the new look. But I think now that most stuff is done that we have less annotations so it is easier to see for the one opening the PR if they agree with the comment.

You can set up such a tool as pre commit hook even to check the files you modified

**Comment by meisterT** [comment]
What `phpcbf` command line do you use?

**Comment by vmcj** [comment]
> What `phpcbf` command line do you use?

phpcbf --standard=.github/workflowscripts/phpruleset.xml webapp/tests/ webapp/src/ webapp/config webapp/public/index.php

**Pull request closed without merging**
