### PR TITLE
Added download submission on the submission details page

### PR DESCRIPTION
**Pull request by rjalfa**
With all the checks.

### CODE REVIEW

**Comment by meisterT** [comment]
That opens up an attack surface. So far, getting access to a team account only meant that you can submit in disguise (which then can be ignored later). But now teams can access other source code.

Do you run DOMjudge in an online judge setting or what's your use case?

I would at least argue that this should be behind an configuration option which is off by default.

**Comment by rjalfa** [comment]
Ya an option would be good.
Download submissions is provided by almost all online judges and is a great option in case we want to see our code or there is a system failure during the contest and migration is not an option. But you rightly said that this should be a disabled-by-default option.
I will try adding that. Thanks

**Comment by rjalfa** [comment]
Also this is good for teams when multiple computers are allowed.

**Comment by thijskh** [comment]
This would be good to have if configurable. But the current documentation is not sufficient. Besides from being configurable, it only offers one file for download. And the team interface has been changed completely since.

We'd accept a PR to this effect but the current code is not mergeable.

**Pull request closed without merging**
