### PR TITLE
Check for CRITICAL and ERROR in symfony log.

### PR DESCRIPTION
**Pull request by meisterT**
This should inform us how much work needs to be done for #1379.

### CODE REVIEW

**Comment by vmcj** [comment]
Should we also just fail if we get these errors?

**Comment by meisterT** [comment]
Maybe - I didn't check that CI run yet whether it would be a lot of work to clean up

**Comment by vmcj** [comment]
> Maybe - I didn't check that CI run yet whether it would be a lot of work to clean up

I'm now introducing your commit in other branches and then fixing the issues, currently that would be only 1 left which I think is a real problem as we try to freeze a contest which cannot be frozen.

**Comment by vmcj** [comment]
This was now contained in: https://github.com/DOMjudge/domjudge/pull/1442

**Pull request closed without merging**
