### PR TITLE
ui: problem_list: fix line break

### PR DESCRIPTION
**Pull request by undefined-moe**

### CODE REVIEW

**Comment by vmcj** [comment]
Hi @undefined-moe,

Can you show a screenshot from the before and after so we can see why this is better?

**Comment by cubercsl** [comment]
I think `</br>` should be shown a new line, but it  show as itself. You can verify this in demoweb.

**Comment by cubercsl** [comment]
Before:
image
After:
image

**Comment by vmcj** [comment]
Yes that's indeed a bug.

I personally don't like to have Unicode chars for this but can't think of something else for now. Can you add a comment above explaining what it does (and/or explain the issue in your commit message)?

**Comment by moesoha** [comment]
> I personally don't like to have Unicode chars for this but can't think of something else for now.

I recommend using something like `{{ '\n' ~ label }}` to prevent this.

**Comment by nickygerritsen** [comment]
> > I personally don't like to have Unicode chars for this but can't think of something else for now.
> 
> I recommend using something like `{{ '\n' ~ label }}` to prevent this.

Or even just `{{ '\n' }}`? I think I prefer that

**Comment by vmcj** [comment]
@undefined-moe can you squash the commits and rewrite your commit message?

**Comment by undefined-moe** [comment]
well there's "squash and merge" if you expand that dropdown besides "merge pull request" button.

**Comment by nickygerritsen** [comment]
We use merge queues, and then that button is not there anymore

**Review by vmcj — APPROVED** [review]
Verified and this fixes the original issue.

It does not work on `/jury/problems/problemset` but we can look into that later.

**Comment by cubercsl** [comment]
> Verified and this fixes the original issue.
> 
> It does not work on `/jury/problems/problemset` but we can look into that later.

@vmcj It looks like ` $('[data-bs-toggle="tooltip"]').tooltip();` is called in `/jury/problems/problemset` but not in `/public`.

**Comment by vmcj** [comment]
@cubercsl, my remark was not meant that we need a fix now (as it was already broken before),

Feel free to create a PR for it. This does add the `<br>` back though? IIRC the newline did not work for the preview problemset page so I think that's that page we should change and not the other ones. Maybe this discussion works better in a new issue though as we're now commenting on a closed PR.

**Pull request merged**
