### PR TITLE
Validate team and role in submit client.

### PR DESCRIPTION
**Pull request by meisterT**

### CODE REVIEW

**Review by nickygerritsen — APPROVED** [review]

**Review by eldering — APPROVED** [review]

**Comment by thijskh** [comment]
What is the rationale?

**Comment by meisterT** [comment]
It turns errors like this:
```
{"code":403,"message":"Forbidden"}
[Dec 20 18:52:26.909] submit/submit[26543]: error: Submission failed (code 403)
```

or worse in dev mode:
```
{"code":403,"message":"Access Denied by controller annotation @IsGranted(\"ROLE_TEAM\")","class":"Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException","trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"/home/sitowert/domjudge/lib/vendor/symfony/security-http/Firewall/ExceptionListener.php","line":137,"args":[]},{"namespace":"Symfony\\Component\\Security\\Http\\Firewall","short_class":"ExceptionListener","class":"Symfony\\Component\\Security\\Http\\Firewall\\ExceptionListener","type":"->","function":"handleAccessDeniedException","file":"/home/sitowert/domjudge/lib/vendor/symfony/security-http/Firewall/ExceptionListener.php","line":102,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\ExceptionEvent"],["object","Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException"]]},{"namespace":"Symfony\\Component\\Security\\Http\\Firewall","short_class":"ExceptionListener","class":"Symfony\\Component\\Security\\Http\\Firewall\\ExceptionListener","type":"->","function":"onKernelException","file":"/home/sitowert/domjudge/lib/vendor/symfony/event-dispatcher/Debug/WrappedListener.php","line":126,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\ExceptionEvent"],["string","kernel.exception"],["object","Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"]]},{"namespace":"Symfony\\Component\\EventDispatcher\\Debug","short_class":"WrappedListener","class":"Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener","type":"->","function":"__invoke","file":"/home/sitowert/domjudge/lib/vendor/symfony/event-dispatcher/EventDispatcher.php","line":264,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\ExceptionEvent"],["string","kernel.exception"],["object","Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"]]},{"namespace":"Symfony\\Component\\EventDispatcher","short_class":"EventDispatcher","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","function":"doDispatch","file":"/home/sitowert/domjudge/lib/vendor/symfony/event-dispatcher/EventDispatcher.php","line":239,"args":[["array",[["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"]]],["string","kernel.exception"],["object","Symfony\\Component\\HttpKernel\\Event\\ExceptionEvent"]]},{"namespace":"Symfony\\Component\\EventDispatcher","short_class":"EventDispatcher","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","function":"callListeners","file":"/home/sitowert/domjudge/lib/vendor/symfony/event-dispatcher/EventDispatcher.php","line":73,"args":[["array",[["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"]]],["string","kernel.exception"],["object","Symfony\\Component\\HttpKernel\\Event\\ExceptionEvent"]]},{"namespace":"Symfony\\Component\\EventDispatcher","short_class":"EventDispatcher","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","function":"dispatch","file":"/home/sitowert/domjudge/lib/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php","line":168,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\ExceptionEvent"],["string","kernel.exception"]]},{"namespace":"Symfony\\Component\\EventDispatcher\\Debug","short_class":"TraceableEventDispatcher","class":"Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher","type":"->","function":"dispatch","file":"/home/sitowert/domjudge/lib/vendor/symfony/http-kernel/HttpKernel.php","line":219,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\ExceptionEvent"],["string","kernel.exception"]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"HttpKernel","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->","function":"handleThrowable","file":"/home/sitowert/domjudge/lib/vendor/symfony/http-kernel/HttpKernel.php","line":91,"args":[["object","Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException"],["object","Symfony\\Component\\HttpFoundation\\Request"],["integer",1]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"HttpKernel","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->","function":"handle","file":"/home/sitowert/domjudge/lib/vendor/symfony/http-kernel/Kernel.php","line":201,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["integer",1],["boolean",true]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"Kernel","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->","function":"handle","file":"/home/sitowert/domjudge/webapp/public/index.php","line":25,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"]]}]}
[Dec 20 18:51:06.028] submit/submit[26332]: error: Submission failed (code 403)
```

into this:
```
[Dec 20 18:50:39.654] submit/submit[26297]: error: User is not associated with a team, contact contest administrator.
```

What are your concerns?

**Comment by thijskh** [comment]
I wonder why we cannot turn the Access denied error into something more informative that states this is the problem, since it will solve it generically instead of just when using the submit client.

**Comment by nickygerritsen** [comment]
I think we can somehow add a message when permission is not granted and then “allow it through” to users but I’m not sure. It is a FOSRest feature afaik

**Comment by nickygerritsen** [comment]
> I think we can somehow add a message when permission is not granted and then “allow it through” to users but I’m not sure. It is a FOSRest feature afaik

Turns out we intended to do this all the time but I broke it when upgrading FOSrest. #946 fixes this and improves the message.

**Comment by thijskh** [comment]
I prefer the approach in #946 because it works generically, not for this submit client only, but also is a lot less code and it does not require one additional API call for each submission for a condition that should hardly ever happen in a normal contest setting.

**Pull request closed without merging**
