### PR TITLE
Add contest name to title elements.

### PR DESCRIPTION
**Pull request by thijskh**
So if you have multiple tabs open you can see which one is which.

I've done this for pages that are specific to a contest: scoreboard, problemset, submissions, balloons, analysis. It does not make sense to me to do it globally. e.g. "Configuration settings NWERC20" is not a good title since the configuration settings are not contest specific.

### CODE REVIEW

**Review by nickygerritsen — COMMENTED** [review]
I believe some of these pages can be accessed without an active contest and just display a message. If so these are now broken. Might be good to add a null check?

Otherwise looks good!

**Review by ubergeek42 — APPROVED** [review]
Nice!

**Comment by thijskh** [comment]
@nickygerritsen How is a "null check" different from the `| default('')` that I'm using?

**Comment by nickygerritsen** [comment]
> @nickygerritsen How is a "null check" different from the `| default('')` that I'm using?

lol was looking on phone. But does that work with `current_contest.something` if `current_contest` is null? If so go ahead and merge

**Pull request merged**
