### PR TITLE
Allow problems to be hidden until another problem is solved.

### PR DESCRIPTION
**Pull request by SolalPirelli**
As discussed on the mailing list, here's the PR.

I'm not a PHP expert by any means, nor do I know the domjudge codebase, so there may be a better way to do it. Also, I guess I should add something about this feature to the admin manual?

### CODE REVIEW

**Comment by meisterT** [comment]
Am I right that the (hidden) problem is still submittable, shows up in the scoreboard and teams can view clarification answers? Isn't that confusing for the teams?

**Comment by SolalPirelli** [comment]
IMHO the scoreboard should show all problems so teams can know who did what; the point is not to have a secret number of problems, or to hide the existence of certain problems, only to disable them until teams have solved the previous one.

Making hidden problems unsubmittable and hiding clarifications for them would probably be better indeed, I'll work on that.

**Comment by SolalPirelli** [comment]
Clarifications for hidden problems are now hidden, hidden problems don't appear in the submit list any more, and the branch has been rebased on top of master. Sorry for the delay.

**Comment by eldering** [comment]
Sorry for not getting back on this sooner.
Ok, I reviewed the pull request, and there are still some issues. In particular, in https://github.com/DOMjudge/domjudge/blob/master/www/team/index.php#L25, https://github.com/DOMjudge/domjudge/blob/master/www/team/upload.php#L64 and https://github.com/DOMjudge/domjudge/blob/master/lib/lib.misc.php#L680 (I may have missed somethin), the query should also incorporate the logic of restricting to problems that are already solved if there is a problem dependency. The best is probably to abstract this away into a function, but we have to think about how to best do this, since at least in `www/team/index.php` the SQL query is retrieving a list of problems instead of checking a single one.
I'll try to look into this soon. Futhermore, I added some changes on top of your pull, see https://github.com/eldering/domjudge/commits/dependent_problems.

**Comment by eldering** [comment]
Closing this because of lack of activity. Feel free to reopen.

**Pull request closed without merging**
